### ISSUE TITLE
readme update

### ISSUE THREAD

**Issue by arthurcorona** [joaojmr26/Chefe-de-Pouca-Coisa#1]
# Chefe de Pouca Coisa
### é um jogo de texto interativo feito em python que consiste em você melhorar sua vila 

<img src="https://user-images.githubusercontent.com/95508790/183786131-9ddfccdb-3c46-44e0-ae53-41a83a5fd445.jpg">

**Comment by joaojmr26** [comment]
Agradeço a participação
